version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: pytest-homeassistant-custom-component
    groups:
      test-dependencies:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
